DataBiosphere/terra-scientific-pipelines-service-cli

.github/workflows/bump-build-publish-cli.yml, pyproject.toml
Attempt to fix the new tag/version generation:
- don't add a SNAPSHOT suffix to the tag that's written as the new version in pyproject.toml
- fix current pyproject.toml that got written with that suffix from the previous run
https://broadworkbench.atlassian.net/browse/TSPS-349
=> TSPS-349 fix: remove -SNAPSHOT suffix from tag

.github/workflows/bump-build-publish-cli.yml, .github/workflows/test-cli.yml
Previous attempt to get versioning working properly failed - it made the new tag but still built the older version (and errored out on push to pypi since that version already existed). 
- that PR: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/4
- failed run: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/actions/runs/11673105487/job/32503125043
This is another attempt to get the tag/build parts to work properly. Here we explicitly request the newly created tag that the bumper job has just created, before building the package and publishing to PyPi.
https://broadworkbench.atlassian.net/browse/TSPS-349
=> TSPS-349 another fix attempt: request the new tag

terralab/config.py, tests/test_config.py
The package downloaded from PyPi still wasn't able to access the config file, though the config file was present in the package. Used the strategy described [here](https://stackoverflow.com/questions/6028000/how-to-read-a-static-file-from-inside-a-python-package) ([importlib](https://docs.python.org/3.11/library/importlib.resources.html)).
https://broadworkbench.atlassian.net/browse/TSPS-363
=> TSPS-363 another fix attempt: use importlib to read config file

terralab/auth_helper.py, terralab/client.py, terralab/commands/pipeline_runs_commands.py, terralab/config.py, terralab/logic/auth_logic.py, terralab/logic/pipeline_runs_logic.py, tests/commands/test_pipeline_runs_commands.py, tests/logic/test_auth_logic.py, tests/logic/test_pipeline_runs_logic.py, tests/test_auth_helper.py
Add use of refresh tokens to avoid timeouts after long uploads.
Strategy:
- Check for a valid access token; if one exists, use it
- Otherwise, check for a refresh token; if one exists, attempt to get and save new tokens
- If refresh attempt fails or if no refresh token is found, prompt user to login via browser
Demo after logging in:
```
➜  rm ~/.terralab/access_token 
➜  terralab --debug pipelines list
Log level set to: DEBUG
Imported config with values: OrderedDict({'TEASPOONS_API_URL': 'https://tsps.dsde-dev.broadinstitute.org', 'SERVER_PORT': '10444', 'OAUTH_OPENID_CONFIGURATION_URI': 'https://terradevb2c.b2clogin.com/terradevb2c.onmicrosoft.com/b2c_1a_signup_signin_dev/v2.0/.well-known/openid-configuration', 'OAUTH_CLIENT_ID': 'bbd07d43-01cb-4b69-8fd0-5746d9a5c9fe', …
```
=> TSPS-373 fix token timeout

poetry.lock, pyproject.toml, terralab/.terralab-cli-config, terralab/commands/auth_commands.py, terralab/commands/pipeline_runs_commands.py, terralab/logic/auth_logic.py, terralab/logic/pipeline_runs_logic.py, tests/commands/test_pipeline_runs_commands.py, tests/logic/test_pipeline_runs_logic.py
This PR is related to https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/170
This PR does three things
* update commands to only require pipeline name when necessary
* update jobs list command to return the pipeline_name
* change the help text for the logout command (we should talk about this!)
https://broadworkbench.atlassian.net/browse/TSPS-382
=> TSPS-382 get commands working without having to pass in pipeline name 

poetry.lock, pyproject.toml, terralab/.terralab-cli-config, terralab/commands/pipeline_runs_commands.py, terralab/commands/pipelines_commands.py, terralab/logic/pipelines_logic.py, tests/commands/test_pipeline_runs_commands.py, tests/commands/test_pipelines_commands.py, tests/logic/test_pipelines_logic.py
Made changes regarding pipeline version
* submit endpoint no longer requires a pipeline version and the service will default to the latest version
* pipeline details now takes an optional pipeline version input, also defaults to latest
* pipeline details and pipelines list now return pipeline version 
Note this will require https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/171 to be merged before it will be working
https://broadworkbench.atlassian.net/browse/TSPS-370
Pipelines
Submit
=> TSPS-370 Make pipelineVersion acceptable and not required 

terralab/log.py, tests/test_log.py
Don't error out if there's a None value in a row to be formatted into a table via tabulate.
Functionally successful in not erroring out when calling `terralab jobs list` with a Preparing job:
https://broadworkbench.atlassian.net/browse/TSPS-388
=> TSPS-388 Process None values in tabulate tables

poetry.lock, pyproject.toml, terralab/logic/pipeline_runs_logic.py, tests/commands/test_pipeline_runs_commands.py, tests/logic/test_pipeline_runs_logic.py
Supporting the change in the Teaspoons service to move the user-provided description input from the start endpoint to the prepare endpoint.
Note: Must merge https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/180 first and then update the thin client version here.
Local test: submitting a job and aborting during upload (so we're stopped before the start endpoint has been called) has effectively incorporated the description:
https://broadworkbench.atlassian.net/browse/TSPS-388
=> TSPS-388 Move description to prepare endpoint

.github/workflows/run-e2e-tests.yml
We want the CLI e2e test to run once a week, not nightly.
https://broadworkbench.atlassian.net/browse/TSPS-331
=> TSPS-331 FIX: CLI e2e test runs once a week

terralab/commands/pipelines_commands.py, terralab/log.py, tests/commands/test_pipelines_commands.py
Before:
``` 
> terralab pipelines list
Found 1 available pipeline:
array_imputation
Version: 0
Phase and impute genotypes using Beagle 5.4 with the AoU/AnVIL reference panel of 515,579 samples.
```
After:
``` 
> terralab pipelines list
Found 1 available pipeline:
Name              Version    Description
----------------  ---------  ----------------------------------------------------
array_imputation  0          Phase and impute genotypes using Beagle 5.4 with the
AoU/AnVIL reference panel of 515,579 samples.
```
https://broadworkbench.atlassian.net/browse/TSPS-407
=> TSPS-407 Improve pipelines list output

terralab/commands/pipeline_runs_commands.py, terralab/commands/pipelines_commands.py, terralab/constants.py, terralab/log.py, terralab/logic/pipeline_runs_logic.py, terralab/utils.py, tests/commands/test_pipeline_runs_commands.py, tests/commands/test_pipelines_commands.py, tests/logic/test_pipeline_runs_logic.py
Add the text "For help troubleshooting, email scientific-services-support@broadinstitute.org" to failed job details response and all API error responses.
Example jobs details for a failed job:
```
✗ terralab jobs details 8ef861be-d548-44e6-aeea-312a0eb8c24b
Status: Failed
Error message: Not all runs succeeded for submission: 82099128-b6f7-4236-ad45-061fb1339a26
For help troubleshooting, email scientific-services-support@broadinstitute.org
Details:
Pipeline Name: array_imputation
Pipeline Version: 0
Submitted: 2024-12-11 13:35:27 EST
Completed: 2024-12-11 13:39:42 EST
Description: 
```
Error that's not an API error doesn't have the help text:
```
✗ terralab jobs details 8ef861be-d548-44e6-aeea-312a0eb8c24 
Input error: JOB_ID must be a valid uuid.
```
Error that's an API error does have …
=> TSPS-396 add support text to failed run response and API errors

.github/actions/create-bee/action.yml, .github/workflows/run-e2e-tests.yml
On top of making the e2e work with the staging deploy hook, we also want to remove the cron job test
This PR accomplishes a similar thing to https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/190 in the cli repo
https://broadworkbench.atlassian.net/browse/TSPS-424
=> TSPS-424 update e2e test to work with post staging deploy hook 

.github/workflows/bump-build-publish-cli.yml, .github/workflows/run-e2e-tests.yml, terralab/.terralab-cli-config
This PR changes the GHA workflow logic to run e2e tests as part of the build-publish workflow (which is run on merge to main), allowing us to set the tag to the new one created when publishing it.
Also remove `continue-on-retry` from the bee-create job (this was a vestige of having a retry-bee-create job that never worked so we removed it)
=> TSPS-425 Run e2e test on merge to main

terralab/auth_helper.py, tests/test_auth_helper.py
Addresses security finding that the access and refresh token files were being created with read access for other users on the machine:
```
✗ ls -l ~/.terralab      
total 16
-rw-r--r--@ 1 marymorg  staff  1582 Jan 29 14:11 access_token
-rw-r--r--@ 1 marymorg  staff  1774 Jan 29 14:11 refresh_token
```
With this PR, only the user running the command gets access to the files:
```
✗ ls -l ~/.terralab
total 16
-rw-------@ 1 marymorg  staff  1592 Jan 29 14:16 access_token
-rw-------@ 1 marymorg  staff  1780 Jan 29 14:16 refresh_token
```
https://broadworkbench.atlassian.net/browse/TSPS-419
=> TSPS-419 Restrict permissions on token files

poetry.lock, pull_request_template.md, terralab/auth_helper.py, terralab/config.py, terralab/custom_http_server.py, tests/test_auth_helper.py
This PR addresses a low-level security finding from AppSec that our auth flow was using a GET request to submit an authorization code to the local server, which means the code was being stored in the user's browser. Here we change that request to a POST so that the code is not stored in the browser history.
This required adding a custom function (do_POST) inside a class we had previously been importing from the oauth2-cli-auth library but have now customized. We also disabled the do_GET function in our custom class to ensure that we're not ever handling that path.
Note on tests and coverage: We are opting not to add tests for this customized code, since neither unit tests nor e2e tests can easily do so (since it involves browsers and running a local server) but rather we are adding a …
=> TSPS-418 Use POST request to pass auth code

terralab/cli.py
Adding some high-level help text intended to help users get started with terralab.
```
✗ terralab -h
Usage: terralab [OPTIONS] COMMAND [ARGS]...
To submit a job, run `terralab submit PIPELINE_NAME [INPUTS] --description
DESCRIPTION`
For more information about the required inputs for a pipeline, run `terralab
pipelines details PIPELINE_NAME`
To list available pipelines, run `terralab pipelines list`
Options:
--version   Show the version and exit.
-h, --help  Show this message and exit.
Commands:
submit               Submit a job
download             Download all output files from a job
jobs                 Get information about your jobs
jobs list          List your jobs
jobs details       Get the status and details of a job
pipelines            Get information about available pipelines …
```
=> TSPS-397 Add help text to terralab -h

poetry.lock, pyproject.toml, terralab/auth_helper.py, terralab/commands/quotas_commands.py, tests/commands/test_quotas_commands.py, tests/logic/test_quotas_logic.py
We've added quota units to be displayed to the user when they request their quota info:
```
✗ terralab quota array_imputation
Pipeline: array_imputation
Quota Limit: 10000 samples
Quota Used: 500 samples
Quota Available: 9500 samples
```
Note tests will fail here until the service PR is merged and this PR has been updated with the new client version.
https://broadworkbench.atlassian.net/browse/TSPS-405
=> TSPS-405 Add quota units to quota info response

terralab/commands/quotas_commands.py, tests/commands/test_quotas_commands.py
Because we run a wdl to calculate the quota for a pipeline run, there's a lag of a few minutes between when a user submits a job and that job being factored into their quota as returned by `terralab quota array_imputation`. Here we're adding a note to the CLI output of that call to warn users about this delay.
```
✗ terralab quota array_imputation
Note: It may take a few minutes for recently submitted jobs to be reflected.
Pipeline: array_imputation
Quota Limit: 10000
Quota Used: 4000
Quota Available: 6000
```
https://broadworkbench.atlassian.net/browse/TSPS-406
=> TSPS-406 Add disclaimer about quota update time

terralab/log.py, terralab/utils.py, tests/commands/test_pipelines_commands.py, tests/test_log.py, tests/test_utils.py
Before:
After:
Running CLI w/o debug mode set:
Running CLI w/ debug mode set:
https://broadworkbench.atlassian.net/browse/TSPS-383
1. Main flow: run `terralab logout` and then `terralab pipelines list` - should prompt a browser login
2. Refresh token flow: run `rm ~/.terralab/access_token` and then `terralab pipelines list` - should succeed without a browser login
=> TSPS-383 Clean up connection error messages

poetry.lock, pyproject.toml, terralab/commands/pipeline_runs_commands.py, tests/commands/test_pipeline_runs_commands.py
Seems like CI will fail until [this PR ](https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/221) is merged and the client published.
Before:
After:
https://broadworkbench.atlassian.net/browse/TSPS-505
1. Main flow: run `terralab logout` and then `terralab pipelines list` - should prompt a browser login
2. Refresh token flow: run `rm ~/.terralab/access_token` and then `terralab pipelines list` - should succeed without a browser login
=> [TSPS-505] Display quotaConsumed in pipeline runs list

pyproject.toml, terralab/auth_helper.py, tests/test_auth_helper.py
Opens the login page with the custom Scientific Services branding.
Note that this will not show any branding differences until the terraform PR is applied ([link](https://github.com/broadinstitute/terraform-ap-deployments/pull/1874)). However, you can still have some confidence that this change has the intended effect by following these steps:
1) Run `terralab logout`
2) Run `terralab pipelines list`
3) Note that `&brand=scientificServices` is now at the end of the login page URL
https://broadworkbench.atlassian.net/browse/TSPS-499
1. Main flow: run `terralab logout` and then `terralab pipelines list` - should prompt a browser login
2. Refresh token flow: run `rm ~/.terralab/access_token` and then `terralab pipelines list` - should succeed without a browser login
=> [TSPS-499] Open login page with custom b2c branding
